### ISSUE TITLE
Compatibility with Xperia (and others)

### ISSUE THREAD

**Issue by Ingvix** [Ruditimmermans/harbour-sailorgram-turing#1]
I understand you're only developing on Turing phone but do you have any specific reason this would not work so well on other devices, like Xperia? You weren't really that specific with the changes you made. I tried your fork with Xperia and so far haven't seen anything broken. Could performance and impact on battery be worse on other devices?

Also a bit of a shame you didn't enable comments in your Openrepos page.

**Comment by Ruditimmermans** [comment]
Hi, the most changes i have made where into the events like sound and the lost messages and other few bug fixes i found, well the mean of this is only for a Turing phone as it would compiled with a old SDK and the app is not up to date for the lasted version it can work on a X but it is never tested, on a Turing the deamon eat a lot of battery that's why i have remove this the code is still there and i will try ti make it better and fix it later on.... About the comments well i have disable it for request etc as it's only for a Turing and as i told above not for the regular user.... so there will be comming ot mutch comments for thing i dont plan or will do, for the X you have the other new client so nothing to do with this one.

**Comment by Ruditimmermans** [comment]
Your welcome ;)
